name: Publish module to Powershell Gallery

on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    # Publishing the module to powershell gallery        
      - name: Publish to Powershell Gallery
        uses: pcgeek86/publish-powershell-module-action@v20
        id: publish-module
        with:
          NuGetApiKey: ${{ secrets.NUGETAPIKEY }} # Using the NugetAPI key set in GitHub Secrets